### ISSUE TITLE
Add "Notebook" tab for users with permission

### ISSUE THREAD

**Issue by spitz-dan-l** [smartscheduling/chatto-hub#105]
The notebook tab will not be associated per-project, it will just be a top-level tab.

It should just link the user over to the jupyterhub server, which we need to give the correct domain and certificate.

The challenging part is that the tab should only appear for users that have accepted an invitation to a specific github team.

@SpencerCDixon is this enough info for you to get started on this? Should I do the github-related legwork?

**Comment by SpencerCDixon** [comment]
Where do I find the link over to the jupyterhub server? whats uri and what info needs to be passed through? I thought you said you can't pass info via params to jupyterhub

**Comment by spitz-dan-l** [comment]
No info to pass thru, and currently the URI is https://54.221.200.95/
