### ISSUE TITLE
Add "Explore" tab to include Rob's visual query builder in an i-frame

### ISSUE THREAD

**Issue by cmoses8626** [smartscheduling/chatto-hub#108]
Code is here: https://github.com/rjstretch/MIMIC-VisualQuery

**Comment by SpencerCDixon** [comment]
looks like we'd have to convert the rails app into an engine and then mount the engine, not a trivial process.  We can go with iFrame once this is deployed @spitz-dan-l

**Comment by robamaton** [comment]
Done
