### ISSUE TITLE
Can't access criticaldata.chatto.io

### ISSUE THREAD

**Issue by spitz-dan-l** [smartscheduling/chatto-hub#111]
Error page reads:

Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

@SpencerCDixon feel free to change the estimate I just guessed

**Comment by SpencerCDixon** [comment]
what URI is this? I dont see an error

**Comment by SpencerCDixon** [comment]
I'll look at logs though

**Comment by spitz-dan-l** [comment]
@SpencerCDixon yep it's back. It was the main page, http://criticaldata.chatto.io/, but it's working now
