### ISSUE TITLE
change button styling so they're a little easier to read

### ISSUE THREAD

**Issue by cmoses8626** [smartscheduling/chatto-hub#19]
button color rgb(66, 133, 244)
font-family something like: Helvetica, arial, nimbussansl, liberationsans, freesans, clean, sans-serif, 'Segoe UI Emoji', 'Segoe UI Symbol'; (copied from github)
font-size: 13px
font-weight: bold

**Comment by SpencerCDixon** [comment]
which buttons? the ones on the main page?
