### ISSUE TITLE
Create github repo when clicking "View on Github" button

### ISSUE THREAD

**Issue by cmoses8626** [smartscheduling/chatto-hub#24]
(and make sure that it automatically creates a repo when creating a new project)

**Comment by SpencerCDixon** [comment]
I don't think it should create a repo when click on "view" that doesn't make sense.  It should probably just create the repo when the project gets created and the view button is just  way for visitors of the site/authetnticated users to see where the repo is located for specific projects

**Comment by cmoses8626** [comment]
My bad, that's what I meant in my comment, was just cross referencing the
Create Project functionality
