### ISSUE TITLE
Add /pricing page

### ISSUE THREAD

**Issue by cmoses8626** [smartscheduling/chatto-hub#65]
Content TBD from Chris

**Comment by SpencerCDixon** [comment]
Pricing page for what?  I'm confused

**Comment by cmoses8626** [comment]
Haven't discussed with team yet, but version 2 of Chatto (Hub) will be
opened up to paying customers for whom we build and deploy predictive
models.

**Comment by SpencerCDixon** [comment]
Word good to know. Glad I spent the time to do lots of refactoring/test coverage then haha

**Comment by cmoses8626** [comment]
there's a grand plan for everything... :)
