### ISSUE TITLE
Special characters break Slack integration

### ISSUE THREAD

**Issue by cmoses8626** [smartscheduling/chatto-hub#83]
Channels with special character get replaced with _
Might add a verification to remove any disallowed characters

**Comment by SpencerCDixon** [comment]
K, so what characters are we not allowing?

**Comment by cmoses8626** [comment]
Period, question mark, exclamation mark, spaces - are the ones I know of.

**Comment by cmoses8626** [comment]
@SpencerCDixon Got an Application Error when name was "New 2 project [": An error occurred in the application and your page could not be served. Please try again in a few moments. If you are the application owner, check your logs for details.

I think numbers are OK, but any of the other special characters seem to break it.

**Comment by SpencerCDixon** [comment]
lol okay.  Not sure how important a validaiton that is to have unless people are like trying to break it.  I'll see if its an easy fix and weigh costs. probably a regex available that finds all special characters

**Comment by SpencerCDixon** [comment]
yeah its super easy, be fixed in 1 min
