### ISSUE TITLE
Content for Getting Started page on chatto.io

### ISSUE THREAD

**Issue by cmoses8626** [smartscheduling/chatto-hub#84]
@SpencerCDixon this is for the non-Critical Data site.

Overview
Chatto is a suite of tools designed for the modern health care company to build smarter health care apps faster. The goal of Chatto is to accelerate product innovation and improve the quality of predictive models in medicine without the need to build your own data science team and HIPAA-compliant infrastructure, thus letting you do what you do best, whether that’s building the next generation EHR or delivering better medical care.

Predictive Model Factory
When you join a project on Chatto, you can upload data in any format to our HIPAA-compliant server for analysis and predictive model development by our expert data science team. When new data is made available, predictive models are automatically refreshed and redeployed, ensuring model predictions are as accurate and up-to-date as possible.

API Marketplace
Predictive models are exposed as a web service for easy integration into your product or service. Easily get access to other predictive models hosted on Chatto or propose brand new projects to meet your needs. Our vision is to crowdsource a marketplace of community-generated models to drive continuous improvement and create best practices.

Track Performance
Daily API requests are tracked and displayed on your project dashboard. You only pay for what you use. Speak to our team to join our beta and discuss pricing.

Feedback
We designed Chatto to accelerate product innovation in health care. We’d love to hear feedback from people on ways to improve it. Whether it be a bug or feature request, please shoot us an email to dev@smartscheduling.io and let us know what you think!

**Comment by SpencerCDixon** [comment]
![screen shot 2015-08-11 at 3 37 53 pm](https://cloud.githubusercontent.com/assets/7471018/9207999/f99b4f88-403e-11e5-959b-2136c8e13756.png)

**Comment by SpencerCDixon** [comment]
@cmoses8626 thats what it looks like

**Comment by SpencerCDixon** [comment]
if acceptable, please close issue

**Comment by cmoses8626** [comment]
let's add more periods to the first paragraph, so use this instead:

Chatto is a suite of tools designed for the modern health care company to build smarter health care apps faster. The goal of Chatto is to accelerate product innovation and improve the quality of predictive models in medicine. We'll provide the data science team and HIPAA-compliant infrastructure. You focus on what you do best, whether that’s building the next generation EHR or delivering better medical care.

**Comment by cmoses8626** [comment]
Also change "Collaborate on clinical data mining" to "Build smarter health apps faster"

**Comment by SpencerCDixon** [comment]
Cool
