### ISSUE TITLE
Change font bebas to Langdon

### ISSUE THREAD

**Issue by cmoses8626** [smartscheduling/chatto-hub#94]
When using Langdon for the headers, need to use all caps to prevent it from using the lowercase font that has weird shadow effect

**Comment by cmoses8626** [comment]
@SpencerCDixon could you bang this out this week? The website needs to get launched shortly.

**Comment by SpencerCDixon** [comment]
@cmoses8626 where do I get Langdon from? Its not on google fonts

**Comment by cmoses8626** [comment]
http://www.fontsquirrel.com/fonts/langdon

**Comment by SpencerCDixon** [comment]
yeah thats one I downloaded cool
