### ISSUE TITLE
Make sure that criticaldata.chatto.io is performant enough for the Hackathon

### ISSUE THREAD

**Issue by robamaton** [smartscheduling/chatto-hub#99]
Evaluate Heroku options, or possibly move to AWS.

**Comment by cmoses8626** [comment]
@robamaton @SpencerCDixon can we just pull the trigger on this? If Heroku is cheaper, that's fine. Just ask for the credit card when ready.

**Comment by robamaton** [comment]
@SpencerCDixon can you handle this? I think Heroku is the right call, just make sure that we have dedicated capacity for the hackathon.
